INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Iralian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
insert INTO unit_of_measure(description) values ('Teaspoon');
insert INTO unit_of_measure(description) values ('Tablespoon');
insert INTO unit_of_measure(description) values ('Cup');
insert INTO unit_of_measure(description) values ('Pinch');
insert INTO unit_of_measure(description) values ('Ounce');
-- insert into INTO unit_of_measure(descroption) values ('Teaspoon');
